### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Nis5l** [Najsr/League-Of-Legends-Champions-ID-List#1]
Hey, sorry to bother you, but may you tell me where you got this data from? I cant find any data online. I would like to complete the list with the latest champions for a bot, and i have no clue how to get them instead of maybe getting data with the riot API and comparing it, but there has to be a easier, less time consuming way right?

**Comment by Najsr** [comment]
Hey,
I don't know where I got it when I made it but I found this JSON file that contains as a 'key' property under each Champion object
http://ddragon.leagueoflegends.com/cdn/10.12.1/data/en_US/champion.json

**Comment by Nis5l** [comment]
Thank you very much...
